coffee:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: nespresso
    brew_temp:
      required: false
      default: medium
      selector:
        select:
          options:
            - low
            - medium
            - high
          translation_key: brew_temperature
    brew_type:
      required: false
      default: lungo
      selector:
        select:
          options:
            - ristretto
            - espresso
            - lungo
            - americano
            - hot_water
          translation_key: brew_type
    coffee_ml:
      required: false
      selector:
        number:
          min: 15
          max: 130
          step: 1
          unit_of_measurement: ml
          mode: slider
    water_ml:
      required: false
      selector:
        number:
          min: 25
          max: 300
          step: 1
          unit_of_measurement: ml
          mode: slider
caps:
  fields:
    device_id:
      required: false
      selector:
        device:
          integration: nespresso
    caps:
      required: true
      default: 100
      selector:
        number:
          min: 1
          max: 1000
          step: 1
          mode: box
